const Product = [
  {
    id: 1,
    image: "/images/potato.jpeg",
    name: "Potato",
    category: "Vegetables",
    price: "2.5₹/kg",
    description: "Fresh and nutritious potatoes",
    shelfLife: "2 weeks",
  },
  {
    id: 2,
    image: "/images/tomato.jpeg",
    name: "Tomato",
    category: "Vegetables",
    price: "3.0₹/kg",
    description: "Juicy and ripe tomatoes",
    shelfLife: "1 week",
  },
  {
    id: 3,
    image: "/images/carrot.jpeg",
    name: "Carrot",
    category: "Vegetables",
    price: "2.2₹/kg",
    description: "Crunchy and sweet carrots",
    shelfLife: "2 weeks",
  },
  {
    id: 4,
    image: "/images/broccoli.jpeg",
    name: "Broccoli",
    category: "Vegetables",
    price: "3.5₹/kg",
    description: "Nutrient-rich broccoli florets",
    shelfLife: "1 week",
  },
  {
    id: 5,
    image: "/images/spinach.jpeg",
    name: "Spinach",
    category: "Vegetables",
    price: "2.8₹/kg",
    description: "Fresh and green spinach leaves",
    shelfLife: "1 week",
  },
  {
    id: 6,
    image: "/images/bell-pepper.jpeg",
    name: "Bell Pepper",
    category: "Vegetables",
    price: "4.0₹/kg",
    description: "Colorful and flavorful bell peppers",
    shelfLife: "2 weeks",
  },
  {
    id: 7,
    image: "/images/onion.jpeg",
    name: "Onion",
    category: "Vegetables",
    price: "2.0₹/kg",
    description: "Sweet and aromatic onions",
    shelfLife: "3 weeks",
  },
  {
    id: 8,
    image: "/images/apple.jpeg",
    name: "Apple",
    category: "Fruits",
    price: "4.0₹/kg",
    description: "Crisp and sweet apples",
    shelfLife: "2 weeks",
  },
  {
    id: 9,
    image: "/images/banana.jpeg",
    name: "Banana",
    category: "Fruits",
    price: "2.0₹/kg",
    description: "Ripe and healthy bananas",
    shelfLife: "1 week",
  },
  {
    id: 10,
    image: "/images/orange.jpeg",
    name: "Orange",
    category: "Fruits",
    price: "3.5₹/kg",
    description: "Juicy and tangy oranges",
    shelfLife: "2 weeks",
  },
  {
    id: 11,
    image: "/images/strawberry.jpeg",
    name: "Strawberry",
    category: "Fruits",
    price: "5.0₹/kg",
    description: "Sweet and succulent strawberries",
    shelfLife: "3 days",
  },
  {
    id: 12,
    image: "/images/grapes.jpeg",
    name: "Grapes",
    category: "Fruits",
    price: "4.2₹/kg",
    description: "Plump and flavorful grapes",
    shelfLife: "1 week",
  },
  {
    id: 13,
    image: "/images/mango.jpeg",
    name: "Mango",
    category: "Fruits",
    price: "3.8₹/kg",
    description: "Tropical and delicious mangoes",
    shelfLife: "1 week",
  },
  {
    id: 14,
    image: "/images/pineapple.jpeg",
    name: "Pineapple",
    category: "Fruits",
    price: "4.5₹/kg",
    description: "Sweet and tangy pineapples",
    shelfLife: "1 week",
  },
  {
    id: 15,
    image: "/images/milk.jpeg",
    name: "Milk",
    category: "Dairy",
    price: "1.5₹/liter",
    description: "Fresh and pure cow's milk",
    shelfLife: "1 week",
  },
  {
    id: 16,
    image: "/images/cheese.jpeg",
    name: "Cheese",
    category: "Dairy",
    price: "8.0₹/kg",
    description: "Creamy and delicious cheese",
    shelfLife: "2 weeks",
  },
  {
    id: 17,
    image: "/images/butter.jpeg",
    name: "Butter",
    category: "Dairy",
    price: "6.5₹/kg",
    description: "Rich and creamy butter",
    shelfLife: "2 weeks",
  },
  {
    id: 18,
    image: "/images/yogurt.jpeg",
    name: "Yogurt",
    category: "Dairy",
    price: "2.0₹/liter",
    description: "Smooth and probiotic yogurt",
    shelfLife: "1 week",
  },
  {
    id: 19,
    image: "/images/eggs.jpeg",
    name: "Eggs",
    category: "Dairy",
    price: "3.5₹/dozen",
    description: "Farm-fresh eggs",
    shelfLife: "2 weeks",
  },
  {
    id: 20,
    image: "/images/cream.jpeg",
    name: "Cream",
    category: "Dairy",
    price: "4.0₹/liter",
    description: "Whipped and silky cream",
    shelfLife: "2 weeks",
  },
  {
    id: 21,
    image: "/images/probiotic-yogurt.jpeg",
    name: "Probiotic Yogurt",
    category: "Dairy",
    price: "2.5₹/liter",
    description: "Probiotic yogurt for a healthy diet",
    shelfLife: "2 weeks",
  },
  {
    id: 22,
    image: "/images/chicken.jpeg",
    name: "Chicken",
    category: "Meat",
    price: "6.0₹/kg",
    description: "Tender and juicy chicken Meat",
    shelfLife: "3 days",
  },
  {
    id: 23,
    image: "/images/fish.jpeg",
    name: "Fish",
    category: "Meat",
    price: "10.0₹/kg",
    description: "Fresh and flavorful fish fillet",
    shelfLife: "2 days",
  },
  {
    id: 24,
    image: "/images/lamb.jpeg",
    name: "Lamb",
    category: "Meat",
    price: "12.0₹/kg",
    description: "Premium quality lamb cuts",
    shelfLife: "4 days",
  },
  {
    id: 25,
    image: "/images/prawns.jpeg",
    name: "Prawns",
    category: "Meat",
    price: "14.5₹/kg",
    description: "Delicate and tasty prawns",
    shelfLife: "2 days",
  },
  {
    id: 26,
    image: "/images/turkey.jpeg",
    name: "Turkey",
    category: "Meat",
    price: "8.0₹/kg",
    description: "Lean and flavorful turkey Meat",
    shelfLife: "3 days",
  },
  {
    id: 27,
    image: "/images/duck.jpeg",
    name: "Duck",
    category: "Meat",
    price: "11.0₹/kg",
    description: "Exquisite duck Meat for special occasions",
    shelfLife: "4 days",
  },
  {
    id: 28,
    image: "/images/rice.jpeg",
    name: "Rice",
    category: "Cereal",
    price: "2.0₹/kg",
    description: "High-quality rice grains",
    shelfLife: "1 year",
  },
  {
    id: 29,
    image: "/images/flour.jpeg",
    name: "Wheat Flour",
    category: "Cereal",
    price: "3.5₹/kg",
    description: "Fine wheat flour for baking",
    shelfLife: "6 months",
  },
  {
    id: 30,
    image: "/images/oats.jpeg",
    name: "Oats",
    category: "Cereal",
    price: "2.8₹/kg",
    description: "Healthy and hearty rolled oats",
    shelfLife: "8 months",
  },
  {
    id: 31,
    image: "/images/cornmeal.jpeg",
    name: "Cornmeal",
    category: "Cereal",
    price: "2.2₹/kg",
    description: "Versatile cornmeal for cooking",
    shelfLife: "10 months",
  },
  {
    id: 32,
    image: "/images/pasta.jpeg",
    name: "Pasta",
    category: "Cereal",
    price: "4.0₹/kg",
    description: "Assorted pasta shapes for delicious dishes",
    shelfLife: "1 year",
  },
  {
    id: 33,
    image: "/images/quinoa.jpeg",
    name: "Quinoa",
    category: "Cereal",
    price: "6.0₹/kg",
    description: "Nutrient-rich quinoa grains",
    shelfLife: "1 year",
  },
  {
    id: 34,
    image: "/images/barley.jpeg",
    name: "Barley",
    category: "Cereal",
    price: "2.5₹/kg",
    description: "Wholesome barley grains for soups and stews",
    shelfLife: "8 months",
  },
];

export default Product;